import { AuthProvider } from "@/components/AuthProvider";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import '@/app/globals.css'

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <AuthProvider>
      <div>
      {children}
      </div>
      
    </AuthProvider>
        
        
  );
}




